import Navbar from './components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Book API App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className='flex bg-gray-300 min-h-screen justify-center items-center'>
          {children}
        </div>
      </body>
    </html>
  )
}
