import './globals.css'

export const metadata = {
  title: 'Book API App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-300 min-h-screen flex justify-center items-center'>

        {children}</body>
    </html>
  )
}
